### PR TITLE
Builds in Go 1.5 now

### LINKED ISSUE #12: Docker build broken with go update
It's been awhile since I've been in goland. Any idea which version of go was being used in the last working build? Currently getting a series of errors:
```
# github.com/statsd/system/pkg/memory
gopath/src/github.com/statsd/system/pkg/memory/memory.go:66: cannot use stat (type *linux.MemInfo) as type linux.MemInfo in argument to percent
gopath/src/github.com/statsd/system/pkg/memory/memory.go:67: cannot use stat (type *linux.MemInfo) as type linux.MemInfo in argument to swapPercent
gopath/src/github.com/statsd/system/pkg/memory/memory.go:70: invalid operation: stat["MemTotal"] (type *linux.MemInfo does not support indexing)
gopath/src/github.com/statsd/system/pkg/memory/memory.go:71: cannot use stat (type *linux.MemInfo) as type linux.MemInfo in argument to used
gopath/src/github.com/statsd/system/pkg/memory/memory.go:72: invalid operation: stat["MemFree"] (type *linux.MemInfo does not support indexing)
gopath/src/github.com/statsd/system/pkg/memory/memory.go:73: invalid operation: stat["Active"] (type *linux.MemInfo does not support indexing)
gopath/src/github.com/statsd/system/pkg/memory/memory.go:74: invalid operation: stat["SwapTotal"] (type *linux.MemInfo does not support indexing)
gopath/src/github.com/statsd/system/pkg/memory/memory.go:75: invalid operation: stat["SwapFree"] (type *linux.MemInfo does not support indexing)
gopath/src/github.com/statsd/system/pkg/memory/memory.go:93: invalid operation: s["SwapTotal"] (type linux.MemInfo does not support indexing)
gopath/src/github.com/statsd/system/pkg/memory/memory.go:94: invalid operation: s["SwapFree"] (type linux.MemInfo does not support indexing)
gopath/src/github.com/statsd/system/pkg/memory/memory.go:94: too many errors
INFO[0079] The command [/bin/sh -c /bin/go-build] returned a non-zero code: 2 
```

### PR DESCRIPTION
**Pull request by ckdarby**
This fixes #12

### CODE REVIEW

**Comment by coderhaoxin** [comment]
+1

**Comment by ckdarby** [comment]
Yo @tj is there anything wrong with this PR ?

**Comment by danielnc** [comment]
+1

**Review by acyberexpert — APPROVED** [review]

**Comment by TransAMrit** [comment]
+1

**Comment by jacekkopecky** [comment]
+1 maintainers?

**Comment by rvdwijngaard** [comment]
+1

**Comment by kkartikeya** [comment]
+1

**Pull request closed without merging**
